### ISSUE TITLE
AttributeError: 'Sanic' object has no attribute 'lazy_umongo'

### ISSUE THREAD

**Issue by tianshuai** [Relrin/sanic-mongodb-extension#17]
```
from sanic_mongodb_ext import MongoDbExtension
from umongo import MotorAsyncIOInstance
def create_app(app_name: str='run') -> Sanic:
    app = Sanic(app_name)

    # load conf
    app.update_config("app/config/base.py")
    app.update_config({"LAZY_UMONGO": MotorAsyncIOInstance()})

    MongoDbExtension(app)
    @app.lazy_umongo.register
    class Artist(Document):
        name = StringField(required=True, allow_none=False)
```

sanic: 23.3.0
sanic-mongodb-extension: 0.5.0

error: AttributeError: 'Sanic' object has no attribute 'lazy_umongo'

Following your case, what is the reason, please!

Solution:
`@app.lazy_umongo.register` chagne `@app.ctx.lazy_umongo.register`

**Comment by Relrin** [comment]
Hello! Thank you for reporting an issue.

After some investigation I discovered the following things:
- The README hasn't been updated. So I did it now. 
- In the one of the latest Sanic major releases, they have introduced a breaking change. And by that reason as a package developers, we have to put the "addons" or custom attributes under the `ctx` space. And therefore any further usage should happen by using the `app.ctx`

So I rolled out the new release of this package. However, it may introduce some breaking changes. Mostly because I have updated all the packages to the latest major releases. And one of them is the uMongo: initially it was the 2nd major release, but I have updated the codebase to use the 3rd one.

Now, just download the latest stable release (which is the `0.6.0`) and try it. Please, let me know if you will face with any issues around this latest release.
